define

  contract sub relationship,
    relates provider,
    relates customer;

  call sub relationship,
    relates caller,
    relates callee,
    has started_at,
    has duration;

  company sub entity,
    plays provider,
    has name;

  person sub entity,
    plays customer,
    plays caller,
    plays callee,
    has first_name,
    has last_name,
    has phone_number,
    has city,
    has age,
    has is_customer;

  name sub attribute datatype string;
  started_at sub attribute datatype date;
  duration sub attribute datatype long;
  first_name sub attribute datatype string;
  last_name sub attribute datatype string;
  phone_number sub attribute datatype string;
  city sub attribute datatype string;
  age sub attribute datatype long;
  is_customer sub attribute datatype boolean;

